### **12. Numpy**

#### **numpy 배열 생성 #1 - np.array 함수**

In [5]:
import numpy as np

x = np.array([1, 2, 3, 4])
print(x)

y = np.array([[2, 3, 4], [1, 2, 5]])
print(y)

print(type(x), type(y))

[1 2 3 4]
[[2 3 4]
 [1 2 5]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


#### **numpy 배열 생성 #2 - np.arange 함수**

In [6]:
import numpy as np

print(np.arange(10))
print(np.arange(1, 10))
print(np.arange(1, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


#### **numpy 배열 생성 #3 - np.ones, np.zeros**

In [7]:
print(np.ones((4, 5)))
print(np.ones((2, 3, 4)))
print(np.zeros((2, 8, 8)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]]


#### **numpy 배열 생성 #4 - np.empty, np.full, np.eye, np.linespace**

In [11]:
print(np.empty((3, 4)))
print(np.full((3, 4, 2), 7))
print(np.eye(3))
print(np.linspace(1, 10, 3))

[[2.70346714e-316 4.94065646e-324 4.94065646e-324 4.94065646e-324]
 [4.94065646e-324 4.94065646e-324 4.94065646e-324 4.94065646e-324]
 [4.94065646e-324 4.94065646e-324 0.00000000e+000 1.46030983e-319]]
[[[7 7]
  [7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]
  [7 7]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1.   5.5 10. ]


#### **reshape 함수 활용**
- ndarray의 형태, 차원을 바꾸기 위해 사용

In [41]:
x = np.arange(1, 16)
print(x)
print(x.shape)

x = x.reshape(5, 3)
print(x.shape)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(15,)
(5, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


#### **ndarray를 활용한 2차원 벡터 곱셈 연산 함수 만들기**

In [72]:
# 임의 크기의 2차원 배열 a, b를 생성
# a[a1][a2], b[b1][b2]에서 a2과 b1은 항상 동일한 크기
# a*b 매트릭스 곱셉을 했을 때, c[a1][b2]가 얻어짐
# a*b 매트릭스 곱셉에 대한 사용자 함수 정의

np.random.seed(10)    # Seed 함수, 동일한 Random 수 생성

# 0, 1사이의 분포로 랜덤한 ndarray 생성
a = np.random.rand(4, 5)
b = np.random.rand(5, 3)

print('a = \n', a)
print('b = \n', b)

def mul_mat(a, b):
  c = np.zeros((len(a), len(b[0])))
  for i in range(len(a)):
    for j in range(len(b[0])):
      temp = 0
      for k in range(len(a[0])):
        temp = temp + a[i][k] * b[k][j]
      c[i][j] = c[i][j] + temp
  return c

c = mul_mat(a, b)
print('c = \n', c)
print('c = \n' ,a.dot(b))

a = 
 [[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
 [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
 [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]
 [0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]]
b = 
 [[0.54254437 0.14217005 0.37334076]
 [0.67413362 0.44183317 0.43401399]
 [0.61776698 0.51313824 0.65039718]
 [0.60103895 0.8052232  0.52164715]
 [0.90864888 0.31923609 0.09045935]]
c = 
 [[1.72694035 1.20607242 1.14480113]
 [0.90722582 0.67410071 0.76074219]
 [2.06322635 1.19255148 1.01291955]
 [2.20010997 1.52288247 1.27516255]]
c = 
 [[1.72694035 1.20607242 1.14480113]
 [0.90722582 0.67410071 0.76074219]
 [2.06322635 1.19255148 1.01291955]
 [2.20010997 1.52288247 1.27516255]]


#### **Indexing and Slicing**

In [82]:
import numpy as np

# 1차원 배열 인덱싱
x = np.arange(10)
print(x)

x[3] = 100
print(x)

# 2차원 배열 인덱싱
x = np.arange(10).reshape(2, 5)
print(x)

print(x[1,-1])
print(x[0])

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2 100   4   5   6   7   8   9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
9
[0 1 2 3 4]


In [88]:
x = np.arange(10)
print(x)
print(x[1:])

x = np.arange(10).reshape(2, 5)
print(x)
print(x[0, :2])
print(x[:2, :2])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1]
[[0 1]
 [5 6]]


#### **Reshaping anid Flatten**
 1. ndarray shape 변경하기

In [89]:
import numpy as np

x = np.arange(15).reshape(3, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [92]:
x = np.arange(36)
print(x)
print(x.shape)
print(x.ndim)

y = x.reshape(6, 6)
print(y.shape)
print(y.ndim)

k = x.reshape(3, 3, -1)
print(k)
print(k.shape)
print(k.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
(36,)
1
(6, 6)
2
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
(3, 3, 4)
3


#### **연산 함수**
 - add, substract, multiply, divide

In [93]:
import numpy as np

x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.30070006 0.11398436 0.82868133 0.04689632 0.62628715]
 [0.54758616 0.819287   0.19894754 0.8568503  0.35165264]
 [0.75464769 0.29596171 0.88393648 0.32551164 0.1650159 ]]


In [94]:
np.add(x, y)

array([[ 0.30070006,  1.11398436,  2.82868133,  3.04689632,  4.62628715],
       [ 5.54758616,  6.819287  ,  7.19894754,  8.8568503 ,  9.35165264],
       [10.75464769, 11.29596171, 12.88393648, 13.32551164, 14.1650159 ]])

In [95]:
np.divide(x, y)

array([[ 0.        ,  8.77313329,  2.41347299, 63.97090516,  6.38684669],
       [ 9.13098322,  7.32344103, 35.1851549 ,  9.33652002, 25.59343793],
       [13.25121658, 37.1669704 , 13.57563612, 39.93712817, 84.8403105 ]])

In [96]:
x + y

array([[ 0.30070006,  1.11398436,  2.82868133,  3.04689632,  4.62628715],
       [ 5.54758616,  6.819287  ,  7.19894754,  8.8568503 ,  9.35165264],
       [10.75464769, 11.29596171, 12.88393648, 13.32551164, 14.1650159 ]])

In [97]:
x / y

array([[ 0.        ,  8.77313329,  2.41347299, 63.97090516,  6.38684669],
       [ 9.13098322,  7.32344103, 35.1851549 ,  9.33652002, 25.59343793],
       [13.25121658, 37.1669704 , 13.57563612, 39.93712817, 84.8403105 ]])

In [98]:
np.mean(y)

0.47439641727920917

In [99]:
np.max(y)

0.8839364795611863

In [100]:
np.argmax(y)

12

In [101]:
np.var(y), np.median(y), np.std(y)

(0.0832608874021029, 0.3516526394320879, 0.2885496272777057)

#### **where 함수**
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [102]:
z = np.random.randn(10)
print(z)

[-0.80459114 -0.21269764 -0.33914025  0.31216994  0.56515267 -0.14742026
 -0.02590534  0.2890942  -0.53987907  0.70816002]


In [103]:
np.where(z > 0, z, 0)

array([0.        , 0.        , 0.        , 0.31216994, 0.56515267,
       0.        , 0.        , 0.2890942 , 0.        , 0.70816002])

#### **Axis**

In [104]:
import numpy as np

x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [105]:
# 1차원 데이터
x = np.arange(15)
print(x)

np.sum(x, axis=0)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


105

In [108]:
# 2차원 데이터
y = x.reshape(3, 5)
print('y = \n', y)
print('y = \n', np.sum(y, axis=0))
print('y = \n', np.sum(y, axis=1))

y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
y = 
 [15 18 21 24 27]
y = 
 [10 35 60]
