#### **13 Numpy - ndarray by Numpy Module**

#### **np.array 함수로 numpy 배열 생성**

In [1]:
import numpy as np

x = np.array([1, 2, 3, 4])
print(x)

y = np.array([[2, 3, 4], [1, 2, 5]])
print(y)

print(type(y))

[1 2 3 4]
[[2 3 4]
 [1 2 5]]
<class 'numpy.ndarray'>


#### **np.arange 함수로 numpy 배열 생성**

In [6]:
import numpy as np

print(np.arange(10))
print(np.arange(1, 10))
print(np.arange(1, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


#### **np.ones, np.zeros로 생성 numpy 배열 생성**

In [9]:
print(np.ones((4, 5)))
print(np.ones((2, 3, 4)))
print(np.zeros((2, 8, 8)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]]


#### **np.empty, np.full로 numpy 배열 생성**

In [10]:
print(np.empty((3, 4)))
print(np.full((3, 4, 2), 7))

[[0.00000000e+000 0.00000000e+000 1.01855798e-312 9.54898106e-313]
 [1.20953760e-312 1.01855798e-312 1.23075756e-312 1.03977794e-312]
 [1.06099790e-312 9.76118064e-313 1.01855798e-312 1.90979621e-312]]
[[[7 7]
  [7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]
  [7 7]]]


#### **np.eye로 생성 numpy 배열 생성**

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### **np.linspace로 생성 numpy 배열 생성**

In [20]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

#### **reshape 함수 활용**
- ndarray의 형태, 차원을 바꾸기 위해 사용

In [19]:
x = np.arange(1, 16)
print(x)
print(x.shape)
x = x.reshape(5, 3)
print(x.shape)
x

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(15,)
(5, 3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])