#### **14 Numpy - ndarray by Random Module**

#### **Random 함수 활용**

In [5]:
import numpy as np

# 0, 1사이의 분포로 랜덤한 ndarray 생성
print(np.random.rand(2, 3))

# 정규분포로 샘플링된 랜덤 ndarray 생성
print(np.random.randn(2, 3))

# 특정 정수 사이에서 랜덤하게 샘플링
print(np.random.randint(1, 100, size=(5,)))

[[0.29412234 0.60388779 0.0360101 ]
 [0.32685119 0.59222639 0.24276106]]
[[-0.03684509  0.58742622 -0.18379014]
 [ 0.94874571 -1.26774813  0.34971905]]
[69 71  8 44  3]


#### **seed 함수; 동일한 결과값 생성**

In [9]:
np.random.seed(10)
np.random.randn(3, 4)

array([[ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556,  0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021,  0.43302619,  1.20303737]])

#### **choice 함수 활용**
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [10]:
np.random.choice(100, size=(3, 4))

array([[72, 78, 49, 51],
       [54, 77, 69, 13],
       [25, 13, 92, 86]])

In [11]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2, 2), replace=False)

array([[3. , 1. ],
       [1.5, 4.9]])

#### **확률분포에 따른 ndarray 생성**
- uniform, normal 등

In [12]:
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[1.13112653, 1.11288837, 2.53091164, 1.02357606, 2.22388668],
       [1.66376451, 2.11929673, 1.67099929, 1.82236509, 1.153711  ],
       [2.70608598, 1.87997491, 1.24390829, 2.46346925, 1.27756493],
       [2.5337601 , 2.66397954, 1.61955611, 2.19516458, 2.74478492]])

In [13]:
np.random.normal(size=(3, 4))
np.random.randn(3, 4)

array([[-1.34306988e+00,  1.45339286e+00,  1.16944865e-03,
        -1.19203847e-02],
       [ 7.15883143e-01, -1.18576855e+00, -6.36327905e-01,
        -6.10813844e-01],
       [-1.31939140e+00, -5.61728416e-01,  2.05384574e-01,
        -9.53360676e-01]])