#### **15 Numpy - ndarray Indexing and Slicing**

In [2]:
import numpy as np

x = np.arange(10)
print(x)

x[3] = 100
print(x)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2 100   4   5   6   7   8   9]


#### **2차원 행렬 인덱싱**

In [19]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [20]:
x[1,-1]

9

In [21]:
x[0]

array([0, 1, 2, 3, 4])

#### **3차원 행렬 인덱싱**

In [22]:
x = np.arange(36).reshape(3, 4, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [23]:
x[1]

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

#### **1차원 벡터 슬라이싱**

In [24]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### **2차원 행렬 슬라이싱**

In [26]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
x[0, :2]

array([0, 1])

In [15]:
x[:1, :2]

array([[0, 1]])

#### **3차원 행렬 슬라이싱**

In [16]:
x = np.arange(54).reshape(2, 9, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [17]:
x[:1, :2, :]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [18]:
x[0, :2, :]

array([[0, 1, 2],
       [3, 4, 5]])