#### **17 Numpy - ndarray Functions**

In [1]:
import numpy as np

x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.29980485 0.28446799 0.64854795 0.77340609 0.97158154]
 [0.76093642 0.90419241 0.29364257 0.98864361 0.67231386]
 [0.70014233 0.19656949 0.33539343 0.17811906 0.77115225]]


#### **연산 함수**
 - add, substract, multiply, divide

In [2]:
np.add(x, y)

array([[ 0.29980485,  1.28446799,  2.64854795,  3.77340609,  4.97158154],
       [ 5.76093642,  6.90419241,  7.29364257,  8.98864361,  9.67231386],
       [10.70014233, 11.19656949, 12.33539343, 13.17811906, 14.77115225]])

In [3]:
np.divide(x, y)

array([[ 0.        ,  3.51533396,  3.08381209,  3.87894538,  4.11699876],
       [ 6.57085121,  6.63575576, 23.83850508,  8.09189468, 13.38660486],
       [14.28281026, 55.9598538 , 35.77887568, 72.98489139, 18.15465102]])

In [4]:
x + y

array([[ 0.29980485,  1.28446799,  2.64854795,  3.77340609,  4.97158154],
       [ 5.76093642,  6.90419241,  7.29364257,  8.98864361,  9.67231386],
       [10.70014233, 11.19656949, 12.33539343, 13.17811906, 14.77115225]])

In [5]:
x / y

array([[ 0.        ,  3.51533396,  3.08381209,  3.87894538,  4.11699876],
       [ 6.57085121,  6.63575576, 23.83850508,  8.09189468, 13.38660486],
       [14.28281026, 55.9598538 , 35.77887568, 72.98489139, 18.15465102]])

#### **통계 함수**
 - 평균, 분산, 중앙, 최대, 최소값 등

In [6]:
print(y)

[[0.29980485 0.28446799 0.64854795 0.77340609 0.97158154]
 [0.76093642 0.90419241 0.29364257 0.98864361 0.67231386]
 [0.70014233 0.19656949 0.33539343 0.17811906 0.77115225]]


In [7]:
np.mean(y)

0.5852609246033081

In [8]:
y.mean()

0.5852609246033081

In [9]:
np.max(y)

0.9886436134218435

In [10]:
np.argmax(y)

8

In [11]:
np.var(y), np.median(y), np.std(y)

(0.07837052570982492, 0.6723138611853305, 0.2799473623912626)

#### **집계함수**
 - 합계(sum), 누적합계(cumsum) 등

In [12]:
y

array([[0.29980485, 0.28446799, 0.64854795, 0.77340609, 0.97158154],
       [0.76093642, 0.90419241, 0.29364257, 0.98864361, 0.67231386],
       [0.70014233, 0.19656949, 0.33539343, 0.17811906, 0.77115225]])

In [13]:
np.sum(y, axis=None)

8.778913869049623

In [14]:
np.cumsum(y)

array([0.29980485, 0.58427285, 1.23282079, 2.00622689, 2.97780843,
       3.73874485, 4.64293726, 4.93657983, 5.92522345, 6.59753731,
       7.29767964, 7.49424913, 7.82964256, 8.00776162, 8.77891387])

#### **any, all 함수**
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [15]:
z = np.random.randn(10)
print(z)

[ 1.07767099 -0.20039966  0.11773171 -0.70218938  0.04946958  0.03343077
 -1.0578747   1.84281177  1.149947    0.2919402 ]


In [16]:
z > 0

array([ True, False,  True, False,  True,  True, False,  True,  True,
        True])

In [17]:
np.any(z > 0)

True

In [18]:
np.all(z != 0)

True

#### **where 함수**
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [19]:
z = np.random.randn(10)
print(z)

[ 0.54670692 -1.67893217  1.20579418  0.21484197 -0.00487704 -0.22794069
 -0.11255283  0.19241642 -0.6238079   0.03741931]


In [20]:
np.where(z > 0, z, 0)

array([0.54670692, 0.        , 1.20579418, 0.21484197, 0.        ,
       0.        , 0.        , 0.19241642, 0.        , 0.03741931])