#### **18 Numpy - Axis**

In [1]:
import numpy as np

x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### **1차원 데이터**

In [6]:
x = np.arange(15)
print(x)

np.sum(x, axis=0)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


105

#### **행렬 데이터**

In [12]:
y = x.reshape(3, 5)
print(y)
print(np.sum(y, axis=0))
print(np.sum(y, axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[15 18 21 24 27]
[10 35 60]


#### **3차 텐서**

In [13]:
z = np.arange(36).reshape(3, 4, 3)
print(z)
print(np.sum(z, axis=0))
print(np.sum(z, axis=1))
print(np.sum(z, axis=2))
print(np.sum(z, axis=-3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
[[36 39 42]
 [45 48 51]
 [54 57 60]
 [63 66 69]]
[[ 18  22  26]
 [ 66  70  74]
 [114 118 122]]
[[  3  12  21  30]
 [ 39  48  57  66]
 [ 75  84  93 102]]
[[36 39 42]
 [45 48 51]
 [54 57 60]
 [63 66 69]]
